"""
Security-role code generator: ``SecurityRole`` object -> Python definition source.

The inverse of importing a role-definition module. Used by ``reverse_role`` to write
``metadata_py/roles/<name>.py`` that round-trips:
``SecurityRole -> source -> exec -> SecurityRole``. The emitted file is also what
``deploy_role`` consumes.
"""

from __future__ import annotations

from typing import Optional

from .components.models import SecurityRole, TablePrivilege


def _emit_table_privilege(tp: TablePrivilege) -> str:
    rights = ", ".join(
        f"AccessRight.{right.name}: PrivilegeDepth.{depth.name}"
        for right, depth in tp.rights.items()
    )
    return f"TablePrivilege(table={tp.table!r}, rights={{{rights}}})"


def role_to_python_source(role: SecurityRole, *, header: Optional[list[str]] = None) -> str:
    """Emit a full ``<name>.py`` role-definition module from a SecurityRole."""
    lines: list[str] = []
    if header:
        lines.extend(header)
    else:
        lines.append(
            f'"""Definition for security role {role.name} (generated by framework_power)."""'
        )
    lines.append("")
    lines.append("from framework_power import (")
    lines.append("    AccessRight, PrivilegeDepth, SecurityRole, TablePrivilege,")
    lines.append(")")
    lines.append("")
    lines.append("ROLE: SecurityRole = SecurityRole(")
    lines.append(f"    name={role.name!r},")
    if role.table_privileges:
        lines.append("    table_privileges=[")
        for tp in role.table_privileges:
            lines.append(f"        {_emit_table_privilege(tp)},")
        lines.append("    ],")
    lines.append(")")
    return "\n".join(lines) + "\n"
