"""
Solution code generator: ``Solution`` object -> Python definition source.

The inverse of importing a solution-definition module. Used by the solution reverse
exporter to write ``metadata_py/solutions/<unique_name>.py`` that round-trips:
``Solution -> source -> exec -> Solution``. The emitted file is also what
``deploy_solution`` consumes, so a reverse-generated file is forward-syncable.

Tables are emitted as NAME REFS (a string list resolved by the table registry at
deploy); each populated non-table component type is emitted as inline model
literals via that type's registered ``codegen`` function. New types registered in
``COMPONENT_TYPES`` are emitted automatically — this module does not change per wave.
"""

from __future__ import annotations

from typing import Any, Optional

from .components import COMPONENT_DEPLOY_ORDER, COMPONENT_TYPES
from .components.models import ComponentRef, Publisher, Solution


def _emit_publisher(pub: Publisher) -> str:
    parts = [
        f"name={pub.name!r}",
        f"display_name={pub.display_name!r}",
        f"prefix={pub.prefix!r}",
    ]
    if pub.description:
        parts.append(f"description={pub.description!r}")
    return "Publisher(" + ", ".join(parts) + ")"


def _emit_ref(ref: ComponentRef) -> str:
    kwargs = [f"type={ref.type!r}"]
    if ref.name:
        kwargs.append(f"name={ref.name!r}")
    if ref.object_id:
        kwargs.append(f"object_id={ref.object_id!r}")
    if ref.entity:
        kwargs.append(f"entity={ref.entity!r}")
    if ref.note:
        kwargs.append(f"note={ref.note!r}")
    return "ComponentRef(" + ", ".join(kwargs) + ")"


def solution_to_python_source(solution: Solution, *, header: Optional[list[str]] = None) -> str:
    """Emit a full ``<unique_name>.py`` solution-definition module from a Solution."""
    # Collect populated non-table typed lists (for inline emit) and their import names.
    imports: set[str] = {"Solution"}
    populated: list[tuple[str, Any, list]] = []
    for type_key in COMPONENT_DEPLOY_ORDER:
        if type_key == "table":
            continue
        ctype = COMPONENT_TYPES.get(type_key)
        if ctype is None:
            continue
        items = list(getattr(solution, type_key + "s", []))
        if items:
            populated.append((type_key, ctype, items))
            imports.update(ctype.codegen_imports)
    if solution.publisher is not None:
        imports.add("Publisher")
    if solution.refs:
        imports.add("ComponentRef")

    lines: list[str] = []
    if header:
        lines.extend(header)
    else:
        lines.append(
            f'"""Definition for solution {solution.unique_name} (generated by framework_power)."""'
        )
    lines.append("")
    lines.append("from framework_power import (")
    for name in sorted(imports):
        lines.append(f"    {name},")
    lines.append(")")
    lines.append("")
    lines.append("SOLUTION: Solution = Solution(")
    lines.append(f"    unique_name={solution.unique_name!r},")
    lines.append(f"    friendly_name={solution.friendly_name!r},")
    if solution.version != "1.0.0.0":
        lines.append(f"    version={solution.version!r},")
    if solution.description:
        lines.append(f"    description={solution.description!r},")
    if solution.publisher is not None:
        lines.append(f"    publisher={_emit_publisher(solution.publisher)},")
    elif solution.publisher_key is not None:
        lines.append(f"    publisher_key={solution.publisher_key!r},")
    if solution.tables:
        lines.append("    tables=[" + ", ".join(repr(t) for t in solution.tables) + "],")
    if solution.roles:
        lines.append("    roles=[" + ", ".join(repr(r) for r in solution.roles) + "],")
    for type_key, ctype, items in populated:
        lines.append(f"    {type_key}s=[")
        for model in items:
            lines.append(f"        {ctype.codegen(model)},")
        lines.append("    ],")
    if solution.refs:
        lines.append("    refs=[" + ", ".join(_emit_ref(r) for r in solution.refs) + "],")
    lines.append(")")
    return "\n".join(lines) + "\n"
