"""
Solution code generator: ``Solution`` object -> Python definition source.

The inverse of importing a solution-definition module. Used by the solution reverse
exporter to write ``metadata_py/solutions/<unique_name>.py`` that round-trips:
``Solution -> source -> exec -> Solution``. The emitted file is also what
``deploy_solution`` consumes, so a reverse-generated file is forward-syncable.

Tables are emitted as NAME REFS (a string list resolved by the table registry at
deploy); non-table component types are emitted as inline model literals once their
waves land (Wave 1 emits publisher + tables + refs only).
"""

from __future__ import annotations

from typing import Optional

from .components.models import ComponentRef, Publisher, Solution


def _emit_publisher(pub: Publisher) -> str:
    parts = [
        f"name={pub.name!r}",
        f"display_name={pub.display_name!r}",
        f"prefix={pub.prefix!r}",
    ]
    if pub.description:
        parts.append(f"description={pub.description!r}")
    return "Publisher(" + ", ".join(parts) + ")"


def _emit_ref(ref: ComponentRef) -> str:
    kwargs = [f"type={ref.type!r}"]
    if ref.name:
        kwargs.append(f"name={ref.name!r}")
    if ref.object_id:
        kwargs.append(f"object_id={ref.object_id!r}")
    if ref.entity:
        kwargs.append(f"entity={ref.entity!r}")
    if ref.note:
        kwargs.append(f"note={ref.note!r}")
    return "ComponentRef(" + ", ".join(kwargs) + ")"


def solution_to_python_source(solution: Solution, *, header: Optional[list[str]] = None) -> str:
    """Emit a full ``<unique_name>.py`` solution-definition module from a Solution."""
    lines: list[str] = []
    if header:
        lines.extend(header)
    else:
        lines.append(
            f'"""Definition for solution {solution.unique_name} (generated by framework_power)."""'
        )
    lines.append("")
    lines.append("from framework_power.components.models import (")
    lines.append("    ComponentRef, Publisher, Solution,")
    lines.append(")")
    lines.append("")
    lines.append("SOLUTION: Solution = Solution(")
    lines.append(f"    unique_name={solution.unique_name!r},")
    lines.append(f"    friendly_name={solution.friendly_name!r},")
    if solution.version != "1.0.0.0":
        lines.append(f"    version={solution.version!r},")
    if solution.description:
        lines.append(f"    description={solution.description!r},")
    if solution.publisher is not None:
        lines.append(f"    publisher={_emit_publisher(solution.publisher)},")
    elif solution.publisher_key is not None:
        lines.append(f"    publisher_key={solution.publisher_key!r},")
    if solution.tables:
        lines.append("    tables=[" + ", ".join(repr(t) for t in solution.tables) + "],")
    if solution.refs:
        lines.append("    refs=[" + ", ".join(_emit_ref(r) for r in solution.refs) + "],")
    lines.append(")")
    return "\n".join(lines) + "\n"
