"""CPQ Main form (refined from auto-created) — framework_power."""

from framework_power import Form, FormType, FormTab, FormColumn, FormSection, FormRow, FormCell, FormControl, FormLabel, FormLibrary, FormEvent, FormEventHandler

FORM: Form = Form(
    name='Information',
    entity='new_quote',
    form_type=FormType.Main,
    description='new_quote main form',
    tabs=[
        FormTab(
            name='GENERAL_TAB',
            id='',
            labels=[
                FormLabel(
                    description='常规',
                    languagecode='2052'
                )
            ],
            columns=[
                FormColumn(
                    width='100%',
                    sections=[
                        FormSection(
                            name='General_Section',
                            id='',
                            columns=1,
                            labels=[
                                FormLabel(
                                    description='常规信息',
                                    languagecode='2052'
                                )
                            ],
                            rows=[
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_name',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_name',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_status',
                                                classid='{3EF39988-22BB-4f0b-BBBE-64B5A3748AEE}',
                                                id='new_status',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_approvalstatus',
                                                classid='{3EF39988-22BB-4f0b-BBBE-64B5A3748AEE}',
                                                id='new_approvalstatus',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_paymentterms',
                                                classid='{3EF39988-22BB-4f0b-BBBE-64B5A3748AEE}',
                                                id='new_paymentterms',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_quotedate',
                                                classid='{5B773807-9FB2-42db-97C3-7A91EFF8ADFF}',
                                                id='new_quotedate',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_validuntil',
                                                classid='{5B773807-9FB2-42db-97C3-7A91EFF8ADFF}',
                                                id='new_validuntil',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_totalamount',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_totalamount',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_totaldiscount',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_totaldiscount',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_remarks',
                                                classid='{B0C872A3-3FA8-4D39-87D3-B3DCDA23B145}',
                                                id='new_remarks',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_inquiry_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_inquiry_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_account_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_account_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_contact_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_contact_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_pricelist_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_pricelist_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_shippingterm_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_shippingterm_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_targetcountry_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_targetcountry_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_salesperson_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_salesperson_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_convertedpo_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_convertedpo_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                )
                            ],
                            showlabel=True,
                            attrs={}
                        )
                    ],
                    attrs={}
                )
            ],
            showlabel=True,
            expanded=True,
            attrs={}
        )
    ],
    libraries=[],
    events=[],
    root_attrs={},
    extras_pre_xml='',
    extras_post_xml=''
)
