"""CPQ Main form (refined) + JS libraries + OnLoad handler — framework_power."""

from framework_power import Form, FormType, FormTab, FormColumn, FormSection, FormRow, FormCell, FormControl, FormLabel, FormLibrary, FormEvent, FormEventHandler

FORM: Form = Form(
    name='Information',
    entity='new_quotedetail',
    form_type=FormType.Main,
    description='new_quotedetail main form',
    tabs=[
        FormTab(
            name='GENERAL_TAB',
            id='',
            labels=[
                FormLabel(
                    description='常规',
                    languagecode='2052'
                )
            ],
            columns=[
                FormColumn(
                    width='100%',
                    sections=[
                        FormSection(
                            name='General_Section',
                            id='',
                            columns=1,
                            labels=[
                                FormLabel(
                                    description='常规信息',
                                    languagecode='2052'
                                )
                            ],
                            rows=[
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_name',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_name',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_qty',
                                                classid='{C6D124CA-7EDA-4a60-AEA9-7FB8D318B68F}',
                                                id='new_qty',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_unitprice',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_unitprice',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_standardprice',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_standardprice',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_discount',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_discount',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_linetotal',
                                                classid='{4273EDBD-AC1D-40D3-9FB2-095C621B552D}',
                                                id='new_linetotal',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_requesteddelivery',
                                                classid='{5B773807-9FB2-42db-97C3-7A91EFF8ADFF}',
                                                id='new_requesteddelivery',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_quote_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_quote_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_product_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_product_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                ),
                                FormRow(
                                    cells=[
                                        FormCell(
                                            control=FormControl(
                                                datafieldname='new_vehiclemodel_id',
                                                classid='{270BD3DB-D9AF-4782-9025-509E298DEC0A}',
                                                id='new_vehiclemodel_id',
                                                disabled=False,
                                                attrs={},
                                                parameters={}
                                            ),
                                            id='',
                                            showlabel=True,
                                            visible=True,
                                            labels=[],
                                            attrs={}
                                        )
                                    ],
                                    attrs={}
                                )
                            ],
                            showlabel=True,
                            attrs={}
                        )
                    ],
                    attrs={}
                )
            ],
            showlabel=True,
            expanded=True,
            attrs={}
        )
    ],
    libraries=[
        FormLibrary(
            name='new_/shared/js/XRM.Common.js',
            library_unique_id=''
        ),
        FormLibrary(
            name='new_/js/new_quotedetail/new_quotedetail.form.js',
            library_unique_id=''
        )
    ],
    events=[
        FormEvent(
            name='onload',
            active=True,
            application=False,
            handlers=[
                FormEventHandler(
                    function_name='QuoteDetailForm.handleFormLoad',
                    library_name='new_/js/new_quotedetail/new_quotedetail.form.js',
                    handler_unique_id='',
                    enabled=True,
                    parameters='',
                    pass_execution_context=True,
                    internal=False,
                    attrs={}
                )
            ],
            control_id=None,
            attrs={}
        )
    ],
    root_attrs={},
    extras_pre_xml='',
    extras_post_xml=''
)
