"""Migrated from metadata/tables/new_spare_salesorder_additions.yaml -> framework_power definition.

Schema names are preserved as-is (legacy lowercase). Add Label.bilingual +
English names where known. Regenerate via scripts/yaml_to_python_metadata.py.
"""

from framework_power import Column, LookupColumn, Relationship, Table
from framework_power.models import (AttributeType, BooleanLabels, Cascade, CascadeConfig, Label, Option, RequiredLevel)

TABLE: Table = Table(
    schema_name='new_spare_salesorder',
    display_name=Label.zh('备件销售订单'),
    description=Label.zh('备件销售订单表 - 新增字段'),
    ownership_type='UserOwned',
    columns=[
        Column('new_customercode', AttributeType.String, display_name=Label.zh('客户编码'), required=RequiredLevel.None_, max_length=100),
        Column('new_fullcar_qty', AttributeType.Integer, display_name=Label.zh('整车数量（更改字段名称为：SO总数量）'), required=RequiredLevel.None_),
        Column('new_notsendqty', AttributeType.Decimal, display_name=Label.zh('未发数量'), required=RequiredLevel.None_),
        Column('new_sendqty', AttributeType.Decimal, display_name=Label.zh('发货数量'), required=RequiredLevel.None_),
        Column('new_delivery_time', AttributeType.DateTime, display_name=Label.zh('已交货时间'), required=RequiredLevel.None_),
        Column('new_effect_time', AttributeType.DateTime, display_name=Label.zh('生效时间'), required=RequiredLevel.None_),
        Column('new_submit_time', AttributeType.DateTime, display_name=Label.zh('提交时间'), required=RequiredLevel.None_),
        Column('new_balances', AttributeType.Money, display_name=Label.zh('可用资信'), required=RequiredLevel.None_, precision=2, precision_source=2),
        Column('new_balances_Base', AttributeType.Money, display_name=Label.zh('可用资信(基础货币)'), required=RequiredLevel.None_, precision=2, precision_source=2),
        Column('new_limitverification', AttributeType.Picklist, display_name=Label.zh('可用额度校验结果'), required=RequiredLevel.None_, options=[Option(1, Label.zh('成功')), Option(2, Label.zh('失败'))]),
        Column('new_nonprepaymentamount', AttributeType.Money, display_name=Label.zh('非预付款(使用现款)金额'), required=RequiredLevel.None_, precision=2, precision_source=2),
        Column('new_being_payment', AttributeType.Money, display_name=Label.zh('待回款金额'), required=RequiredLevel.None_),
        Column('new_budgetamount', AttributeType.Money, display_name=Label.zh('预算占用金额'), required=RequiredLevel.None_),
        Column('new_gscerrorinfo', AttributeType.String, display_name=Label.zh('预算释放失败信息'), required=RequiredLevel.None_, max_length=2000),
        Column('new_creditreason_type', AttributeType.Picklist, display_name=Label.zh('贷项原因'), required=RequiredLevel.None_, options=[Option(1, Label.zh('价格错误')), Option(2, Label.zh('电商平台价格')), Option(3, Label.zh('补偿质量缺陷')), Option(4, Label.zh('客户关系维护')), Option(5, Label.zh('市场推广')), Option(6, Label.zh('促销')), Option(7, Label.zh('管理层赠送')), Option(8, Label.zh('销售返利')), Option(9, Label.zh('促销优惠价')), Option(10, Label.zh('买赠')), Option(11, Label.zh('平台补贴')), Option(12, Label.zh('售后赔付'))]),
        Column('new_debitreason_type', AttributeType.Picklist, display_name=Label.zh('借项原因'), required=RequiredLevel.None_, options=[Option(8, Label.zh('平台补贴')), Option(7, Label.zh('销售返利')), Option(6, Label.zh('管理层赠送')), Option(5, Label.zh('促销')), Option(4, Label.zh('市场推广')), Option(3, Label.zh('客户关系维护')), Option(2, Label.zh('价格错误')), Option(1, Label.zh('0元样机买断'))]),
        Column('new_company_tax', AttributeType.String, display_name=Label.zh('公司纳税人识别号'), required=RequiredLevel.None_, max_length=100),
        Column('new_contact', AttributeType.String, display_name=Label.zh('收货人'), required=RequiredLevel.None_, max_length=200),
        Column('new_contactphone', AttributeType.String, display_name=Label.zh('收货人电话'), required=RequiredLevel.None_, max_length=200),
        Column('new_consigneeaddress', AttributeType.String, display_name=Label.zh('详细地址'), required=RequiredLevel.None_, max_length=500),
        Column('new_consigneephone', AttributeType.String, display_name=Label.zh('联系电话'), required=RequiredLevel.ApplicationRequired, max_length=100),
        Column('new_terminaldeliveryparty', AttributeType.String, display_name=Label.zh('终端送达方'), required=RequiredLevel.None_, max_length=100),
        Column('new_return_type', AttributeType.Picklist, display_name=Label.zh('退货单类型'), required=RequiredLevel.None_, options=[Option(2, Label.zh('来料不良')), Option(3, Label.zh('DOA')), Option(4, Label.zh('DAP')), Option(5, Label.zh('多维换新')), Option(6, Label.zh('付费换新')), Option(7, Label.zh('七天无理由')), Option(8, Label.zh('正常退货')), Option(9, Label.zh('非正常退货')), Option(10, Label.zh('正常换货')), Option(11, Label.zh('非正常换货')), Option(1, Label.zh('拒收退货'))]),
        Column('new_returnorder_type', AttributeType.Picklist, display_name=Label.zh('退货订单类型'), required=RequiredLevel.None_, options=[Option(3, Label.zh('保内配件拒收退货订单')), Option(2, Label.zh('0元售后退货订单')), Option(1, Label.zh('0元拒收退货订单'))]),
        Column('new_invoiceamount', AttributeType.Money, display_name=Label.zh('已开票金额'), required=RequiredLevel.None_),
        Column('new_invoiceraise', AttributeType.String, display_name=Label.zh('个人/公司发票抬头'), required=RequiredLevel.None_, max_length=100),
        Column('new_invoicetype', AttributeType.Picklist, display_name=Label.zh('发票类型'), required=RequiredLevel.None_, options=[Option(1, Label.zh('增值税普通发票')), Option(2, Label.zh('增值税专用发票')), Option(3, Label.zh('电子发票')), Option(4, Label.zh('普通发票')), Option(5, Label.zh('出口发票'))]),
        Column('new_issap', AttributeType.Boolean, display_name=Label.zh('是否存在sap系统发票'), required=RequiredLevel.None_, boolean_labels=BooleanLabels(Label.zh('是'), Label.zh('否'))),
        Column('new_payment_amount', AttributeType.Money, display_name=Label.zh('已回款金额'), required=RequiredLevel.None_),
        Column('new_curr_approvestep_name', AttributeType.String, display_name=Label.zh('当前审批步骤'), required=RequiredLevel.None_, max_length=100),
        Column('new_curr_approvestep_user', AttributeType.String, display_name=Label.zh('当前审批人'), required=RequiredLevel.None_, max_length=100),
        Column('new_last_approve_time', AttributeType.DateTime, display_name=Label.zh('上一次审批时间'), required=RequiredLevel.None_),
        Column('new_last_approvestep_name', AttributeType.String, display_name=Label.zh('上一个审批步骤'), required=RequiredLevel.None_, max_length=100),
        Column('new_last_approvestep_user', AttributeType.String, display_name=Label.zh('上一个审批人'), required=RequiredLevel.None_, max_length=100),
        Column('new_scssfailreason', AttributeType.String, display_name=Label.zh('SCSS同步失败原因'), required=RequiredLevel.None_, max_length=500),
        Column('new_scssorderno', AttributeType.String, display_name=Label.zh('SCSS 备件订单号'), required=RequiredLevel.None_, max_length=100),
        Column('new_approvalstatus', AttributeType.Picklist, display_name=Label.zh('审核状态'), required=RequiredLevel.None_, options=[Option(1, Label.zh('已创建')), Option(2, Label.zh('审核中')), Option(3, Label.zh('审核通过')), Option(4, Label.zh('审核不通过'))]),
        Column('new_iscopy', AttributeType.Boolean, display_name=Label.zh('是否复制单'), required=RequiredLevel.None_, boolean_labels=BooleanLabels(Label.zh('是'), Label.zh('否'))),
        Column('new_order_qty', AttributeType.Decimal, display_name=Label.zh('订单总数量'), required=RequiredLevel.None_),
        Column('new_source', AttributeType.Picklist, display_name=Label.zh('订单来源'), required=RequiredLevel.None_, options=[Option(1, Label.zh('代理商')), Option(2, Label.zh('京东')), Option(3, Label.zh('天猫')), Option(4, Label.zh('小程序')), Option(5, Label.zh('抖音')), Option(6, Label.zh('官网')), Option(7, Label.zh('门店')), Option(8, Label.zh('门店转代理商')), Option(9, Label.zh('E3')), Option(10, Label.zh('OA'))]),
        Column('new_old_totalamount', AttributeType.Money, display_name=Label.zh('原订单合计'), required=RequiredLevel.None_),
        Column('new_order_time', AttributeType.DateTime, display_name=Label.zh('下单时间'), required=RequiredLevel.None_),
        Column('new_orderdate', AttributeType.DateTime, display_name=Label.zh('订单日期'), required=RequiredLevel.None_),
        Column('new_ordertime', AttributeType.DateTime, display_name=Label.zh('下单时间'), required=RequiredLevel.None_),
        Column('new_originalordertime', AttributeType.DateTime, display_name=Label.zh('原始订单下单时间'), required=RequiredLevel.None_),
        Column('new_reason', AttributeType.Picklist, display_name=Label.zh('退货原因'), required=RequiredLevel.None_, options=[Option(1, Label.zh('仓库误发')), Option(2, Label.zh('客户退款')), Option(3, Label.zh('物流破损')), Option(4, Label.zh('其他'))]),
        Column('new_transport_type', AttributeType.Picklist, display_name=Label.zh('运输方式'), required=RequiredLevel.None_, options=[Option(10, Label.zh('海运')), Option(20, Label.zh('空运'))]),
    ],
    relationships=[
        Relationship(schema_name='new_spare_salesorder_ordforecastorderid_new_ord_forecastorder', referenced_entity='new_ord_forecastorder', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_ord_forecastorder_id', display_name=Label.zh('预测单'), target_entity='new_ord_forecastorder', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_headbusinessunitid_businessunit', referenced_entity='businessunit', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_headbusinessunit_id', display_name=Label.zh('负责人业务部门'), target_entity='businessunit', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_cityid_new_city', referenced_entity='new_city', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_city_id', display_name=Label.zh('收货市'), target_entity='new_city', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_countyid_new_county', referenced_entity='new_county', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_county_id', display_name=Label.zh('收货区/县'), target_entity='new_county', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_provinceid_new_province', referenced_entity='new_province', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_province_id', display_name=Label.zh('收货省/州'), target_entity='new_province', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_invoiceaccountid_account', referenced_entity='account', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_invoiceaccount_id', display_name=Label.zh('开票方'), target_entity='account', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_ordreasonid_new_ord_reason', referenced_entity='new_ord_reason', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_ord_reason_id', display_name=Label.zh('订单原因'), target_entity='new_ord_reason', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_ordtradeid_new_shippingterm', referenced_entity='new_shippingterm', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_ord_trade_id', display_name=Label.zh('国际贸易条款'), target_entity='new_shippingterm', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_ordorisalesorderid_new_spare_salesorder', referenced_entity='new_spare_salesorder', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_ord_ori_salesorder_id', display_name=Label.zh('原计划订单'), target_entity='new_spare_salesorder', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_productgroupid_new_productgroup', referenced_entity='new_productgroup', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_productgroup_id', display_name=Label.zh('产品组'), target_entity='new_productgroup', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
        Relationship(schema_name='new_spare_salesorder_secondbusinessunitid_businessunit', referenced_entity='businessunit', referencing_entity='new_spare_salesorder', lookup=LookupColumn('new_secondbusinessunit_id', display_name=Label.zh('二级业务部门'), target_entity='businessunit', required=RequiredLevel.None_), cascade=CascadeConfig(assign=Cascade.NoCascade, delete=Cascade.RemoveLink, reparent=Cascade.NoCascade, share=Cascade.NoCascade, unshare=Cascade.NoCascade)),
    ],
)
